#Inside these parameters are just dictionaries

param1:
  test: This is a test


#This is an artifact parameter which has a dictionary of directory
artifacts:
  artifacts_dir: artifacts #This is a the directory call artifact where we will be storing/saving information like models, plot etc
  model_dir: model 
  plots_dir: plots 
  model_name: model.h5
  CHECKPOINT_DIR: checkpoints
  plot_name: plot_name


logs:
  logs_dir: logs_dir
  general_logs: general_logs
  TENSORBOARD_ROOT_LOG_DIR: tensorboard_logs


params:
  epochs: 30
  batch_size: 32
  num_classes: 10
  loss_function: sparse_categorical_crossentropy
  metrics: accuracy
  optimizer: SGD
  validation_datasize: 5000
  patience: 5
  restore_best_weights: True